// Centralized cars data used across listing and details pages
// Extend entries with details needed for CarDetailsPage

export const carsData = [
  {
    id: 1,
    name: "BMW 3 Series",
    image: "/assets/cars/bmw-3.png",
    type: "SEDAN",
    year: 2025,
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.0,
    reviews: 127,
    passengers: 4,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "2.0L Turbo",
    features: ["Air Conditioning", "Advanced Safety", "Bluetooth", "GPS Ready"],
    description: "Experience luxury and performance with the BMW 3 Series.",
    location: "Airport Terminal 1",
    pickupInfo: "International Airport, Terminal 1, Rental Car Center, Level 1",
    available: "Available 24/7",
  },
  {
    id: 2,
    name: "Audi A4",
    image: "/assets/featured1.png",
    type: "SEDAN",
    year: 2024,
    price: 259,
    originalPrice: 349,
    discount: 15,
    rating: 4.3,
    reviews: 88,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "2.0L",
    features: ["Air Conditioning", "Bluetooth", "GPS Ready"],
    description: "Compact luxury sedan with smooth ride and tech-forward cabin.",
    location: "City Center",
    pickupInfo: "Downtown Garage, Level 2",
    available: "Available 8AM-10PM",
  },
  {
    id: 3,
    name: "Mercedes GLC",
    image: "/assets/cars/mercedes-glc.png",
    type: "SUV",
    year: 2025,
    price: 349,
    originalPrice: 449,
    discount: 20,
    rating: 4.5,
    reviews: 98,
    passengers: 5,
    luggage: "3 Large Bags",
    transmission: "automatic",
    fuelType: "hybrid",
    engine: "2.0L Turbo",
    features: ["Premium Sound System", "Panoramic Sunroof", "Leather Seats", "Advanced Safety"],
    description: "Luxury SUV with advanced features and comfortable interior.",
    location: "Airport Terminal 1",
    pickupInfo: "International Airport, Terminal 1, Rental Car Center, Level 1",
    available: "Available 24/7",
  },
  {
    id: 4,
    name: "Tesla Model 3",
    image: "/assets/featured2.png",
    type: "ELECTRIC",
    year: 2024,
    price: 329,
    originalPrice: 399,
    discount: 10,
    rating: 4.7,
    reviews: 150,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "electric",
    engine: "Dual Motor",
    features: ["Autopilot", "Heated Seats", "Bluetooth", "GPS Ready"],
    description: "All-electric sedan with exceptional range and technology.",
    location: "Tech Park",
    pickupInfo: "Parking B, Charging Area",
    available: "Available 24/7",
  },
  {
    id: 5,
    name: "Ford Mustang",
    image: "/assets/featured3.png",
    type: "SPORTS",
    year: 2023,
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.6,
    reviews: 77,
    passengers: 4,
    luggage: "1 Large Bag",
    transmission: "manual",
    fuelType: "gasoline",
    engine: "5.0L V8",
    features: ["Sport Suspension", "Premium Sound", "Leather Seats"],
    description: "Iconic sports coupe with thrilling performance.",
    location: "Downtown Showroom",
    pickupInfo: "Front Desk, Level 1",
    available: "Available 9AM-8PM",
  },
  {
    id: 6,
    name: "Range Rover Evoque",
    image: "/assets/featured1.jpg",
    type: "SUV",
    year: 2025,
    price: 459,
    originalPrice: 549,
    discount: 15,
    rating: 4.4,
    reviews: 64,
    passengers: 5,
    luggage: "3 Large Bags",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "2.0L Turbo",
    features: ["Panoramic Roof", "4x4", "Heated Seats"],
    description: "Premium compact SUV built for comfort and capability.",
    location: "Airport Terminal 2",
    pickupInfo: "Rental Center, Gate C",
    available: "Available 24/7",
  },
  {
    id: 7,
    name: "Toyota Corolla",
    image: "/assets/featured3.jpg",
    type: "SEDAN",
    year: 2022,
    price: 129,
    originalPrice: 179,
    discount: 10,
    rating: 4.2,
    reviews: 220,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "1.8L",
    features: ["Air Conditioning", "Bluetooth", "Backup Camera"],
    description: "Reliable and efficient daily driver.",
    location: "Suburban Center",
    pickupInfo: "Lot A",
    available: "Available 7AM-9PM",
  },
  {
    id: 8,
    name: "Honda Civic",
    image: "/assets/featured1.png",
    type: "SEDAN",
    year: 2023,
    price: 149,
    originalPrice: 199,
    discount: 5,
    rating: 4.1,
    reviews: 180,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "2.0L",
    features: ["Bluetooth", "GPS Ready", "Adaptive Cruise"],
    description: "Comfortable compact sedan with modern features.",
    location: "City Center",
    pickupInfo: "Garage 3",
    available: "Available 8AM-11PM",
  },
  {
    id: 9,
    name: "Nissan Leaf",
    image: "/assets/featured2.png",
    type: "ELECTRIC",
    year: 2022,
    price: 189,
    originalPrice: 239,
    discount: 8,
    rating: 4.0,
    reviews: 75,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "electric",
    engine: "EV",
    features: ["Fast Charging", "Bluetooth", "GPS Ready"],
    description: "Affordable electric hatchback perfect for city trips.",
    location: "Tech Park",
    pickupInfo: "Charging Bay 2",
    available: "Available 24/7",
  },
  {
    id: 10,
    name: "BMW X5",
    image: "/assets/featured3.png",
    type: "SUV",
    year: 2024,
    price: 499,
    originalPrice: 599,
    discount: 18,
    rating: 4.8,
    reviews: 140,
    passengers: 5,
    luggage: "4 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "3.0L Turbo",
    features: ["Leather Seats", "Premium Sound", "Adaptive Suspension"],
    description: "Luxury SUV with powerful engine and premium interior.",
    location: "Airport Premium Area",
    pickupInfo: "VIP Desk",
    available: "Available 24/7",
  },
  {
    id: 11,
    name: "Toyota RAV4",
    image: "/assets/featured1.jpg",
    type: "SUV",
    year: 2023,
    price: 209,
    originalPrice: 269,
    discount: 10,
    rating: 4.3,
    reviews: 210,
    passengers: 5,
    luggage: "3 Large Bags",
    transmission: "automatic",
    fuelType: "hybrid",
    engine: "2.5L Hybrid",
    features: ["AWD", "Bluetooth", "GPS Ready"],
    description: "Versatile compact SUV with hybrid efficiency.",
    location: "Suburban Center",
    pickupInfo: "Lot B",
    available: "Available 24/7",
  },
  {
    id: 12,
    name: "Kia Sportage",
    image: "/assets/featured3.jpg",
    type: "SUV",
    year: 2022,
    price: 179,
    originalPrice: 229,
    discount: 12,
    rating: 3.9,
    reviews: 95,
    passengers: 5,
    luggage: "3 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "2.0L",
    features: ["Air Conditioning", "Bluetooth"],
    description: "Value-packed SUV with roomy interior.",
    location: "City Center",
    pickupInfo: "Garage 5",
    available: "Available 7AM-10PM",
  },
  {
    id: 13,
    name: "Porsche 911",
    image: "/assets/featured2.png",
    type: "SPORTS",
    year: 2024,
    price: 799,
    originalPrice: 899,
    discount: 5,
    rating: 4.9,
    reviews: 52,
    passengers: 2,
    luggage: "1 Small Bag",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "3.0L Twin-Turbo",
    features: ["Sport Exhaust", "Ceramic Brakes", "Leather"],
    description: "High-performance coupe for an unforgettable drive.",
    location: "Downtown Showroom",
    pickupInfo: "Performance Desk",
    available: "Available 9AM-7PM",
  },
  {
    id: 14,
    name: "Hyundai Ioniq 5",
    image: "/assets/featured1.png",
    type: "ELECTRIC",
    year: 2024,
    price: 279,
    originalPrice: 329,
    discount: 10,
    rating: 4.6,
    reviews: 130,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "automatic",
    fuelType: "electric",
    engine: "EV",
    features: ["Fast Charging", "Heated Seats", "Bluetooth"],
    description: "Cutting-edge EV with roomy cabin and great range.",
    location: "Tech Park",
    pickupInfo: "Charging Bay 4",
    available: "Available 24/7",
  },
  {
    id: 15,
    name: "Chevrolet Suburban",
    image: "/assets/featured3.png",
    type: "SUV",
    year: 2023,
    price: 389,
    originalPrice: 459,
    discount: 12,
    rating: 4.0,
    reviews: 80,
    passengers: 7,
    luggage: "5 Large Bags",
    transmission: "automatic",
    fuelType: "gasoline",
    engine: "5.3L V8",
    features: ["3rd Row", "Premium Sound", "GPS Ready"],
    description: "Full-size SUV ideal for family trips.",
    location: "Airport Terminal 1",
    pickupInfo: "Large Vehicle Bay",
    available: "Available 24/7",
  },
  {
    id: 16,
    name: "Volkswagen Golf",
    image: "/assets/featured2.png",
    type: "HATCHBACK",
    year: 2022,
    price: 139,
    originalPrice: 189,
    discount: 10,
    rating: 4.1,
    reviews: 160,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "manual",
    fuelType: "gasoline",
    engine: "1.4L Turbo",
    features: ["Bluetooth", "Backup Camera"],
    description: "Fun-to-drive hatchback with efficient engine.",
    location: "City Center",
    pickupInfo: "Garage 2",
    available: "Available 8AM-10PM",
  },
  {
    id: 17,
    name: "BMW 5 Series",
    image: "/assets/cars/bmw-5-series.jpg",
    type: "LUXURY",
    year: 2023,
    price: 349,
    originalPrice: 429,
    discount: 15,
    rating: 4.8,
    reviews: 127,
    passengers: 5,
    luggage: "3 Large Bags",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "2.0L Turbo",
    features: ["Air Conditioning", "Advanced Safety", "Bluetooth", "GPS Ready"],
    description: "Executive sedan with premium comfort and performance.",
    location: "Airport Terminal 1",
    pickupInfo: "Rental Car Center, Level 1",
    available: "Available 24/7",
  },
  {
    id: 18,
    name: "Jeep Wrangler",
    image: "/assets/featured1.jpg",
    type: "SUV",
    year: 2023,
    price: 289,
    originalPrice: 339,
    discount: 8,
    rating: 4.2,
    reviews: 110,
    passengers: 5,
    luggage: "2 Large Bags",
    transmission: "manual",
    fuelType: "gasoline",
    engine: "3.6L",
    features: ["4x4", "Removable Roof", "Bluetooth"],
    description: "Rugged off-roader ready for adventure.",
    location: "Outdoor Lot",
    pickupInfo: "Bay D",
    available: "Available 7AM-9PM",
  },
]

export function getCarById(id) {
  return carsData.find((c) => String(c.id) === String(id)) || null;
}